[PHP]
; Maximum execution time of each script, in seconds
; https://php.net/max-execution-time
max_execution_time = 300

; Maximum amount of memory a script may consume
memory_limit = 256M

; Maximum allowed size of uploaded files
upload_max_filesize = 100M

; Maximum size of POST data that PHP will accept
post_max_size = 100M

; The number of files which can be open by the process
open_basedir = /var/www/html:/tmp
